from rest_framework import serializers

class YourDataSerializer(serializers.Serializer):
    Web = serializers.CharField(max_length=20)
    NganhCon = serializers.CharField(max_length=50)
    Link = serializers.CharField(max_length=300)
    TenCV = serializers.CharField(max_length=300)
    CongTy = serializers.CharField(max_length=300)
    TinhThanh = serializers.CharField(max_length=150)
    LoaiHinh = serializers.CharField(max_length=70)
    HanNopCV = serializers.CharField(max_length=30)
    KinhNghiem =serializers.CharField(max_length=100)
    Luong = serializers.CharField(max_length=100)
    Image = serializers.CharField(max_length=255)
    
class SearchSerializer(serializers.Serializer):
    Web = serializers.CharField(max_length=20)
    NganhCon = serializers.CharField(max_length=50)
    Link = serializers.CharField(max_length=300)
    TenCV = serializers.CharField(max_length=300)
    CongTy = serializers.CharField(max_length=300)
    TinhThanh = serializers.CharField(max_length=150)
    LoaiHinh = serializers.CharField(max_length=70)
    HanNopCV = serializers.CharField(max_length=30)
    KinhNghiem =serializers.CharField(max_length=100)
    Luong = serializers.CharField(max_length=100)
    Image = serializers.CharField(max_length=255)
    ID = serializers.IntegerField()
    MoTa = serializers.CharField()
    YeuCau = serializers.CharField()
    PhucLoi = serializers.CharField()
    CapBac = serializers.CharField(max_length=50)
    LuongTB = serializers.DecimalField(max_digits=10, decimal_places=1)
    KhoangLuong = serializers.CharField()
    SoLuong = serializers.IntegerField()